package com.bruce.gogo.system.model;

/**
 * Roleinfo generated by MyEclipse Persistence Tools
 */

public class Modleinfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private String modelname;

	private String kname;

	private String content;

	private Integer rtype;

	private String permissionid;
	


	// Constructors

	/** default constructor */
	public Modleinfo() {
	}

	/** minimal constructor */
	public Modleinfo( String kname) {
		this.kname = kname;
	}

	/** full constructor */
	public Modleinfo( String modelname, String kname, String content,
			Integer rtype, String permissionid) {
		this.modelname = modelname;
		this.kname = kname;
		this.content = content;
		this.rtype = rtype;
		this.permissionid = permissionid;
		
	}

	// Property accessors

	


	
	public String getKname() {
		return kname;
	}

	public void setKname(String kname) {
		this.kname = kname;
	}



	

	public Integer getRtype() {
		return rtype;
	}

	public String getPermissionid() {
		return this.permissionid;
	}

	public void setPermissionid(String permissionid) {
		this.permissionid = permissionid;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setRtype(Integer rtype) {
		this.rtype = rtype;
	}

	public String getModelname() {
		return modelname;
	}

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}