package com.bruce.gogo.system.model;

/**
 * Permissioninfo generated by MyEclipse Persistence Tools
 */

public class Stmkinfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private String pename;

	private String kname;

	private String isfolder;

	private Integer parentid;

	private String perlink;

	private String ptype;

	private String content;

	private Integer ncom;

	// Constructors

	/** default constructor */
	public Stmkinfo() {
	}

	/** minimal constructor */
	public Stmkinfo(String kname, String isfolder,
			Integer parentid, String ptype) {		
		this.kname = kname;
		this.isfolder = isfolder;
		this.parentid = parentid;
		this.ptype = ptype;
	}

	/** full constructor */
	public Stmkinfo(String pename, String kname,
			String isfolder, Integer parentid, String perlink, String ptype,
			String content, Integer ncom) {		
		this.pename = pename;
		this.kname = kname;
		this.isfolder = isfolder;
		this.parentid = parentid;
		this.perlink = perlink;
		this.ptype = ptype;
		this.content = content;
		this.ncom = ncom;
	}

	// Property accessors

	


	public String getIsfolder() {
		return this.isfolder;
	}

	public void setIsfolder(String isfolder) {
		this.isfolder = isfolder;
	}

	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	

	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPename() {
		return pename;
	}

	public void setPename(String pename) {
		this.pename = pename;
	}

	public String getKname() {
		return kname;
	}

	public void setKname(String kname) {
		this.kname = kname;
	}

	public String getPerlink() {
		return perlink;
	}

	public void setPerlink(String perlink) {
		this.perlink = perlink;
	}

	public Integer getNcom() {
		return ncom;
	}

	public void setNcom(Integer ncom) {
		this.ncom = ncom;
	}



}